trigger:
- main  # Se ejecuta cuando hay cambios en la rama main

pool:
  vmImage: 'Default' # Usamos Windows porque tu captura muestra que trabajas ah√≠

steps:
- task: Gradle@4
  inputs:
    gradleWrapperFile: 'gradlew'
    workingDirectory: '$(System.DefaultWorkingDirectory)/gradlew'
    options: '$(System.DefaultWorkingDirectory)/pipeline en Azure DevOps'
    tasks: 'pipeline en Azure DevOps'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: PublishBuildArtifacts@1
  displayName: 'Guardar Artefactos (CD)'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'